/*Copyright (c) 2016-2017 vcstest2.com All Rights Reserved.
 This software is the confidential and proprietary information of vcstest2.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcstest2.com*/
package com.testmvnbuild.dbscenarios.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testmvnbuild.dbscenarios.AllExternalTypes;
import com.testmvnbuild.dbscenarios.AllExternalTypesId;


/**
 * ServiceImpl object for domain model class AllExternalTypes.
 *
 * @see AllExternalTypes
 */
@Service("dbscenarios.AllExternalTypesService")
public class AllExternalTypesServiceImpl implements AllExternalTypesService {

    private static final Logger LOGGER = LoggerFactory.getLogger(AllExternalTypesServiceImpl.class);


    @Autowired
    @Qualifier("dbscenarios.AllExternalTypesDao")
    private WMGenericDao<AllExternalTypes, AllExternalTypesId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<AllExternalTypes, AllExternalTypesId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "dbscenariosTransactionManager")
    @Override
	public AllExternalTypes create(AllExternalTypes allExternalTypes) {
        LOGGER.debug("Creating a new AllExternalTypes with information: {}", allExternalTypes);
        AllExternalTypes allExternalTypesCreated = this.wmGenericDao.create(allExternalTypes);
        return allExternalTypesCreated;
    }

	@Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public AllExternalTypes getById(AllExternalTypesId allexternaltypesId) throws EntityNotFoundException {
        LOGGER.debug("Finding AllExternalTypes by id: {}", allexternaltypesId);
        AllExternalTypes allExternalTypes = this.wmGenericDao.findById(allexternaltypesId);
        if (allExternalTypes == null){
            LOGGER.debug("No AllExternalTypes found with id: {}", allexternaltypesId);
            throw new EntityNotFoundException(String.valueOf(allexternaltypesId));
        }
        return allExternalTypes;
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public AllExternalTypes findById(AllExternalTypesId allexternaltypesId) {
        LOGGER.debug("Finding AllExternalTypes by id: {}", allexternaltypesId);
        return this.wmGenericDao.findById(allexternaltypesId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "dbscenariosTransactionManager")
	@Override
	public AllExternalTypes update(AllExternalTypes allExternalTypes) throws EntityNotFoundException {
        LOGGER.debug("Updating AllExternalTypes with information: {}", allExternalTypes);
        this.wmGenericDao.update(allExternalTypes);

        AllExternalTypesId allexternaltypesId = new AllExternalTypesId();
        allexternaltypesId.setTinyIntCol(allExternalTypes.getTinyIntCol());
        allexternaltypesId.setSmallIntCol(allExternalTypes.getSmallIntCol());
        allexternaltypesId.setMediumIntCol(allExternalTypes.getMediumIntCol());
        allexternaltypesId.setIntCol(allExternalTypes.getIntCol());
        allexternaltypesId.setBigintCol(allExternalTypes.getBigintCol());
        allexternaltypesId.setDecimalCol(allExternalTypes.getDecimalCol());
        allexternaltypesId.setFloatCol(allExternalTypes.getFloatCol());
        allexternaltypesId.setDoubleCol(allExternalTypes.getDoubleCol());
        allexternaltypesId.setBitCol(allExternalTypes.isBitCol());
        allexternaltypesId.setBooleanCol(allExternalTypes.isBooleanCol());
        allexternaltypesId.setSerialCol(allExternalTypes.getSerialCol());
        allexternaltypesId.setDateCol(allExternalTypes.getDateCol());
        allexternaltypesId.setDatetimeCol(allExternalTypes.getDatetimeCol());
        allexternaltypesId.setTimestampCol(allExternalTypes.getTimestampCol());
        allexternaltypesId.setTimeCol(allExternalTypes.getTimeCol());
        allexternaltypesId.setCharCol(allExternalTypes.getCharCol());
        allexternaltypesId.setVarcharCol(allExternalTypes.getVarcharCol());
        allexternaltypesId.setTinytextCol(allExternalTypes.getTinytextCol());
        allexternaltypesId.setTextCol(allExternalTypes.getTextCol());
        allexternaltypesId.setMediumTextCol(allExternalTypes.getMediumTextCol());
        allexternaltypesId.setLongtextCol(allExternalTypes.getLongtextCol());
        allexternaltypesId.setBlobCol(allExternalTypes.getBlobCol());
        allexternaltypesId.setLongblobCol(allExternalTypes.getLongblobCol());

        return this.wmGenericDao.findById(allexternaltypesId);
    }

    @Transactional(value = "dbscenariosTransactionManager")
	@Override
	public AllExternalTypes delete(AllExternalTypesId allexternaltypesId) throws EntityNotFoundException {
        LOGGER.debug("Deleting AllExternalTypes with id: {}", allexternaltypesId);
        AllExternalTypes deleted = this.wmGenericDao.findById(allexternaltypesId);
        if (deleted == null) {
            LOGGER.debug("No AllExternalTypes found with id: {}", allexternaltypesId);
            throw new EntityNotFoundException(String.valueOf(allexternaltypesId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public Page<AllExternalTypes> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all AllExternalTypes");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
    @Override
    public Page<AllExternalTypes> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all AllExternalTypes");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "dbscenariosTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service dbscenarios for table AllExternalTypes to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "dbscenariosTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }



}

