/*Copyright (c) 2016-2017 vcstest2.com All Rights Reserved.
 This software is the confidential and proprietary information of vcstest2.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcstest2.com*/
package com.testmvnbuild.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.Objects;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

public class AllExternalTypesId implements Serializable {

    private Short tinyIntCol;
    private Short smallIntCol;
    private Integer mediumIntCol;
    private Integer intCol;
    private BigInteger bigintCol;
    private Integer decimalCol;
    private Double floatCol;
    private BigDecimal doubleCol;
    private Boolean bitCol;
    private Boolean booleanCol;
    private BigInteger serialCol;
    private Date dateCol;
    @Type(type = "DateTime")
    private LocalDateTime datetimeCol;
    private Date timestampCol;
    private Date timeCol;
    private Character charCol;
    private String varcharCol;
    private String tinytextCol;
    private String textCol;
    private String mediumTextCol;
    private String longtextCol;
    private byte[] blobCol;
    private byte[] longblobCol;

    public Short getTinyIntCol() {
        return this.tinyIntCol;
    }

    public void setTinyIntCol(Short tinyIntCol) {
        this.tinyIntCol = tinyIntCol;
    }

    public Short getSmallIntCol() {
        return this.smallIntCol;
    }

    public void setSmallIntCol(Short smallIntCol) {
        this.smallIntCol = smallIntCol;
    }

    public Integer getMediumIntCol() {
        return this.mediumIntCol;
    }

    public void setMediumIntCol(Integer mediumIntCol) {
        this.mediumIntCol = mediumIntCol;
    }

    public Integer getIntCol() {
        return this.intCol;
    }

    public void setIntCol(Integer intCol) {
        this.intCol = intCol;
    }

    public BigInteger getBigintCol() {
        return this.bigintCol;
    }

    public void setBigintCol(BigInteger bigintCol) {
        this.bigintCol = bigintCol;
    }

    public Integer getDecimalCol() {
        return this.decimalCol;
    }

    public void setDecimalCol(Integer decimalCol) {
        this.decimalCol = decimalCol;
    }

    public Double getFloatCol() {
        return this.floatCol;
    }

    public void setFloatCol(Double floatCol) {
        this.floatCol = floatCol;
    }

    public BigDecimal getDoubleCol() {
        return this.doubleCol;
    }

    public void setDoubleCol(BigDecimal doubleCol) {
        this.doubleCol = doubleCol;
    }

    public Boolean isBitCol() {
        return this.bitCol;
    }

    public void setBitCol(Boolean bitCol) {
        this.bitCol = bitCol;
    }

    public Boolean isBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }

    public BigInteger getSerialCol() {
        return this.serialCol;
    }

    public void setSerialCol(BigInteger serialCol) {
        this.serialCol = serialCol;
    }

    public Date getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(Date dateCol) {
        this.dateCol = dateCol;
    }

    public LocalDateTime getDatetimeCol() {
        return this.datetimeCol;
    }

    public void setDatetimeCol(LocalDateTime datetimeCol) {
        this.datetimeCol = datetimeCol;
    }

    public Date getTimestampCol() {
        return this.timestampCol;
    }

    public void setTimestampCol(Date timestampCol) {
        this.timestampCol = timestampCol;
    }

    public Date getTimeCol() {
        return this.timeCol;
    }

    public void setTimeCol(Date timeCol) {
        this.timeCol = timeCol;
    }

    public Character getCharCol() {
        return this.charCol;
    }

    public void setCharCol(Character charCol) {
        this.charCol = charCol;
    }

    public String getVarcharCol() {
        return this.varcharCol;
    }

    public void setVarcharCol(String varcharCol) {
        this.varcharCol = varcharCol;
    }

    public String getTinytextCol() {
        return this.tinytextCol;
    }

    public void setTinytextCol(String tinytextCol) {
        this.tinytextCol = tinytextCol;
    }

    public String getTextCol() {
        return this.textCol;
    }

    public void setTextCol(String textCol) {
        this.textCol = textCol;
    }

    public String getMediumTextCol() {
        return this.mediumTextCol;
    }

    public void setMediumTextCol(String mediumTextCol) {
        this.mediumTextCol = mediumTextCol;
    }

    public String getLongtextCol() {
        return this.longtextCol;
    }

    public void setLongtextCol(String longtextCol) {
        this.longtextCol = longtextCol;
    }

    public byte[] getBlobCol() {
        return this.blobCol;
    }

    public void setBlobCol(byte[] blobCol) {
        this.blobCol = blobCol;
    }

    public byte[] getLongblobCol() {
        return this.longblobCol;
    }

    public void setLongblobCol(byte[] longblobCol) {
        this.longblobCol = longblobCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AllExternalTypes)) return false;
        final AllExternalTypes allExternalTypes = (AllExternalTypes) o;
        return Objects.equals(getTinyIntCol(), allExternalTypes.getTinyIntCol()) &&
                Objects.equals(getSmallIntCol(), allExternalTypes.getSmallIntCol()) &&
                Objects.equals(getMediumIntCol(), allExternalTypes.getMediumIntCol()) &&
                Objects.equals(getIntCol(), allExternalTypes.getIntCol()) &&
                Objects.equals(getBigintCol(), allExternalTypes.getBigintCol()) &&
                Objects.equals(getDecimalCol(), allExternalTypes.getDecimalCol()) &&
                Objects.equals(getFloatCol(), allExternalTypes.getFloatCol()) &&
                Objects.equals(getDoubleCol(), allExternalTypes.getDoubleCol()) &&
                Objects.equals(isBitCol(), allExternalTypes.isBitCol()) &&
                Objects.equals(isBooleanCol(), allExternalTypes.isBooleanCol()) &&
                Objects.equals(getSerialCol(), allExternalTypes.getSerialCol()) &&
                Objects.equals(getDateCol(), allExternalTypes.getDateCol()) &&
                Objects.equals(getDatetimeCol(), allExternalTypes.getDatetimeCol()) &&
                Objects.equals(getTimestampCol(), allExternalTypes.getTimestampCol()) &&
                Objects.equals(getTimeCol(), allExternalTypes.getTimeCol()) &&
                Objects.equals(getCharCol(), allExternalTypes.getCharCol()) &&
                Objects.equals(getVarcharCol(), allExternalTypes.getVarcharCol()) &&
                Objects.equals(getTinytextCol(), allExternalTypes.getTinytextCol()) &&
                Objects.equals(getTextCol(), allExternalTypes.getTextCol()) &&
                Objects.equals(getMediumTextCol(), allExternalTypes.getMediumTextCol()) &&
                Objects.equals(getLongtextCol(), allExternalTypes.getLongtextCol()) &&
                Objects.equals(getBlobCol(), allExternalTypes.getBlobCol()) &&
                Objects.equals(getLongblobCol(), allExternalTypes.getLongblobCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTinyIntCol(),
                getSmallIntCol(),
                getMediumIntCol(),
                getIntCol(),
                getBigintCol(),
                getDecimalCol(),
                getFloatCol(),
                getDoubleCol(),
                isBitCol(),
                isBooleanCol(),
                getSerialCol(),
                getDateCol(),
                getDatetimeCol(),
                getTimestampCol(),
                getTimeCol(),
                getCharCol(),
                getVarcharCol(),
                getTinytextCol(),
                getTextCol(),
                getMediumTextCol(),
                getLongtextCol(),
                getBlobCol(),
                getLongblobCol());
    }
}
