/*Copyright (c) 2016-2017 vcstest2.com All Rights Reserved.
 This software is the confidential and proprietary information of vcstest2.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcstest2.com*/
package com.testmvnbuild.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

/**
 * TOne2oneC generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`T ONE2ONE C`")
public class TOne2oneC implements Serializable {

    private String stringCol;
    private short byteId;
    private Boolean booleanCol;
    @Type(type = "DateTime")
    private LocalDateTime datetimeCol;

    @Id
    @Column(name = "`string col`", nullable = false, length = 255)
    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    @Column(name = "`BYTE ID`", nullable = false, scale = 0, precision = 3)
    public short getByteId() {
        return this.byteId;
    }

    public void setByteId(short byteId) {
        this.byteId = byteId;
    }

    @Column(name = "`BOOLEAN COL`", nullable = true)
    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }

    @Column(name = "`DATETIME COL`", nullable = false)
    public LocalDateTime getDatetimeCol() {
        return this.datetimeCol;
    }

    public void setDatetimeCol(LocalDateTime datetimeCol) {
        this.datetimeCol = datetimeCol;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TOne2oneC)) return false;
        final TOne2oneC tone2oneC = (TOne2oneC) o;
        return Objects.equals(getStringCol(), tone2oneC.getStringCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStringCol());
    }
}

