/*Copyright (c) 2016-2017 vcstest2.com All Rights Reserved.
 This software is the confidential and proprietary information of vcstest2.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcstest2.com*/
package com.testmvnbuild.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TOne2oneP generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`T ONE2ONE P`", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"`SERIAL COL`"})})
public class TOne2oneP implements Serializable {

    private Short byteCol;
    private Date dateCol;
    private BigInteger serialCol;
    private Date timeType;
    private char charId;

    @Id
    @Column(name = "`BYTE COL`", nullable = false, scale = 0, precision = 3)
    public Short getByteCol() {
        return this.byteCol;
    }

    public void setByteCol(Short byteCol) {
        this.byteCol = byteCol;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "`DATE COL`", nullable = false)
    public Date getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(Date dateCol) {
        this.dateCol = dateCol;
    }

    @Column(name = "`SERIAL COL`", nullable = false, scale = 0, precision = 20)
    public BigInteger getSerialCol() {
        return this.serialCol;
    }

    public void setSerialCol(BigInteger serialCol) {
        this.serialCol = serialCol;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "`TIME TYPE`", nullable = false)
    public Date getTimeType() {
        return this.timeType;
    }

    public void setTimeType(Date timeType) {
        this.timeType = timeType;
    }

    @Column(name = "`CHAR ID`", nullable = false, length = 1)
    public char getCharId() {
        return this.charId;
    }

    public void setCharId(char charId) {
        this.charId = charId;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TOne2oneP)) return false;
        final TOne2oneP tone2oneP = (TOne2oneP) o;
        return Objects.equals(getByteCol(), tone2oneP.getByteCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getByteCol());
    }
}

