/*Copyright (c) 2016-2017 vcstest2.com All Rights Reserved.
 This software is the confidential and proprietary information of vcstest2.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcstest2.com*/
package com.testmvnbuild.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class TUcComposites2Id implements Serializable {

    private Short byteId;
    private Character charCol;
    private String stringCol;
    private String column5;

    public Short getByteId() {
        return this.byteId;
    }

    public void setByteId(Short byteId) {
        this.byteId = byteId;
    }

    public Character getCharCol() {
        return this.charCol;
    }

    public void setCharCol(Character charCol) {
        this.charCol = charCol;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    public String getColumn5() {
        return this.column5;
    }

    public void setColumn5(String column5) {
        this.column5 = column5;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TUcComposites2)) return false;
        final TUcComposites2 tucComposites2 = (TUcComposites2) o;
        return Objects.equals(getByteId(), tucComposites2.getByteId()) &&
                Objects.equals(getCharCol(), tucComposites2.getCharCol()) &&
                Objects.equals(getStringCol(), tucComposites2.getStringCol()) &&
                Objects.equals(getColumn5(), tucComposites2.getColumn5());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getByteId(),
                getCharCol(),
                getStringCol(),
                getColumn5());
    }
}
