/*Copyright (c) 2016-2017 vcstest2.com All Rights Reserved.
 This software is the confidential and proprietary information of vcstest2.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcstest2.com*/
package com.testmvnbuild.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * TUcComposites2 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`T UC COMPOSITES2`")
@IdClass(TUcComposites2Id.class)
public class TUcComposites2 implements Serializable {

    private Short byteId;
    private Character charCol;
    private String stringCol;
    private String column5;
    private short shortCol;

    @Id
    @Column(name = "`BYTE ID`", nullable = false, scale = 0, precision = 3)
    public Short getByteId() {
        return this.byteId;
    }

    public void setByteId(Short byteId) {
        this.byteId = byteId;
    }

    @Id
    @Column(name = "`CHAR COL`", nullable = false, length = 1)
    public Character getCharCol() {
        return this.charCol;
    }

    public void setCharCol(Character charCol) {
        this.charCol = charCol;
    }

    @Id
    @Column(name = "`STRING COL`", nullable = false, length = 255)
    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    @Id
    @Column(name = "`COLUMN5`", nullable = false, length = 255)
    public String getColumn5() {
        return this.column5;
    }

    public void setColumn5(String column5) {
        this.column5 = column5;
    }

    @Column(name = "`SHORT COL`", nullable = false, scale = 0, precision = 5)
    public short getShortCol() {
        return this.shortCol;
    }

    public void setShortCol(short shortCol) {
        this.shortCol = shortCol;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TUcComposites2)) return false;
        final TUcComposites2 tucComposites2 = (TUcComposites2) o;
        return Objects.equals(getByteId(), tucComposites2.getByteId()) &&
                Objects.equals(getCharCol(), tucComposites2.getCharCol()) &&
                Objects.equals(getStringCol(), tucComposites2.getStringCol()) &&
                Objects.equals(getColumn5(), tucComposites2.getColumn5());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getByteId(),
                getCharCol(),
                getStringCol(),
                getColumn5());
    }
}

